config/routes.rb
Friends::Application.routes.draw do

  root :to => "home#index"
  devise_for :users, :skip => [:registrations]
  devise_scope :user do
    get 'users/edit' => 'devise/registrations#edit', as: 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  # resources :users

  namespace :admin do
    match "pages/:id/new" => 'pages#new', as: :new_nested
    resources :pages do
      resources :images
    end
  
  end
  match '/admin' => 'admin/pages#index', as: :admin_home

  match "/:id" => 'pages#show', as: :top_page
  match "/:id/:nested_id" => 'pages#nested', as: :nested_page
  match "/:id/:nested_id/:nested_page_id" => 'pages#deep_nested', as: :deeply_nested_page


end

app/models/image.rb
class Image < ActiveRecord::Base
  attr_accessible :caption, :image_name, :image_uid, :link_image, :image, :imageable_id, :imageable_type
  image_accessor :image
  before_create :default_name

  belongs_to :imageable, :polymorphic => true

  def default_name
  	self.image_name ||= File.basename(image.filename, '.*').titleize if image
  end
end

app/models/page.rb
class Page < ActiveRecord::Base
	extend FriendlyId
  Linguistics.use(:en)
  
  attr_accessible :content, :title, :publish, :parent_id, :parent_branch, :images_attributes, :link_color, :background_color,
                  :image_name, :image_uid, :image, :friendly_title, :videos_attributes
  
  before_create :title_to_friendly_title
  before_create :default_name
  after_create :setup_slugs

  scope :published, where(publish: true)

  image_accessor :image
	friendly_id :friendly_title, use: :slugged
  
  has_many :children, class_name: "Page", foreign_key: "parent_id"
  belongs_to :parent, class_name: "Page"
  has_many :videos
  accepts_nested_attributes_for :videos, :allow_destroy => true


  has_many :images, :as => :imageable
  accepts_nested_attributes_for :images, :allow_destroy => true
 
  validates :title, presence: true
  private
  
  def title_to_friendly_title
    self.friendly_title = (self.title.en.numwords == "") ? self.title : self.title.en.numwords
  end

  def default_name
    self.image_name ||= File.basename(image.filename, '.*').titleize if image
  end

  def setup_slugs
    self.slug = self.friendly_title
    self.save
  end

end

app/models/thumb.rb
class Thumb < ActiveRecord::Base
  attr_accessible :job, :uid
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  
end

app/models/video.rb
class Video < ActiveRecord::Base
  attr_accessible :page_id, :video
  belongs_to :page
end

app/controllers/admin/base_controller.rb
module Admin
  class BaseController < ApplicationController
    before_filter :authenticate_user!
  	layout :admin_layout

  	private
  	def admin_layout
  		"admin"
  	end
  end
end

app/controllers/admin/images_controller.rb
module Admin
	class ImagesController < BaseController
	  def index
	    @images = Image.all
	  end

	  def new
	  	@page = Page.find(params[:page_id])
	  	@images = @page.images
	    @image = Image.new
	  end

	  def show
	    @image = Image.find(params[:id])
	  end

	  def edit
	    @image = Image.find(params[:id])
	  end

	  def create
	    @image = Image.create(params[:image])
	  end

	  def update
	    @image = Image.find(params[:id])
	    if @image.update_attributes(params[:image])
	      redirect_to admin_images_url, notice: 'Image was successfully updated!'
	    else
	      render 'edit'
	    end
	  end

	  def destroy
	    @image = Image.find(params[:id])
	    if @image.destroy
	    	redirect_to :back, notice: 'Image was deleted'
	    else
	    	redirect_to :back, notice: 'Image could not be deleted!'
	    end
	  end

	end
end

app/controllers/admin/pages_controller.rb
module Admin
	class PagesController < BaseController
	  def index
	    @pages = Page.find(:all, :order => "created_at")
	  end

	  def new
	    @parent_page = Page.find(params[:id])
	    @page = Page.new
	  end

	  def show
	    @page = Page.find(params[:id])
	  end

	  def edit
	    @page = Page.find(params[:id])
	  end

	  def create
	    @page = Page.new(params[:page])
	    if @page.save
	      redirect_to admin_pages_url, notice: 'Page was successfully added!'
	    else
	      render 'new'
	    end
	  end

	  def update
	    @page = Page.find(params[:id])
	    if @page.update_attributes(params[:page])
	      redirect_to admin_pages_url, notice: 'Page was successfully updated!'
	    else
	      render 'edit'
	    end
	  end

	  def destroy
	    @page = Page.find(params[:id])
	    if @page.destroy
	      redirect_to admin_pages_url, notice: 'Page was successfully deleted!'
	    else
	      render 'index'
	    end
	  end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  layout :layout

  private

  def layout
  	if devise_controller?
  		"admin"
  	else
  		"application"
  	end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @pages = Page.all
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @pages = Page.all
  end

  def show
    @page = Page.find(params[:id])
  end

  def nested
    @page = Page.find(params[:id])
    @nested_page = Page.find(params[:nested_id])
  end

  def deep_nested
    @page = Page.find(params[:id])
    @nested_page = Page.find(params[:nested_id])
    @deep_nested_page = Page.find(params[:nested_page_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def make_url_array_or_default
    content = Page.find_by_title('?').content
    content.present? ? content.split(',') : %w(http://google.com)
  end

  def random_url
    content = Page.find_by_title('?').content
    content.present? ? content.split(',').shuffle.first : root_url
  end

  def icon(name, content)
    raw("<i class=\"icon-#{name}\"></i> ") + content
  end
  
  def is_active?(path)
    "active" if current_page?(path)
  end
  
  def is_current?(path)
    current_page?(path)
  end
  
  def content_tag_for(url, title, id)
    content_tag(:li, link_to( is_current?(url) ? icon("share-alt", title) : title, url, class: is_active?(url), id: id))
  end

  def link_to_add_fields(name, f, association, opts = {})
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    css_class = opts[:class].present? ? "add_fields #{opts[:class]}" : "add_fields"
    link_to(name, '#', class: css_class, data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/home_helper.rb
module HomeHelper

  def link_gifs
    css = ''
    Page.published.each do |p|
      if p.parent.nil? && p.image.present?
        link = p.link_color.present? ? p.link_color : '#eceaf0'
        css += '.' + p.title.downcase + '-hover {background-image: url(' + p.image.remote_url + ');} '
        css += '.' + p.title.downcase + '-link-hover {color:' + link + '; text-decoration:none;} ' 
      end
    end
    css += 'a {color:#eceaf0} a:hover {color:#eceaf0; text-decoration:none;} body {background-color:#191919}'
    css
  end

  def find_gif(title)
    Page.find_by_title(title).image.remote_url if Page.find_by_title(title).image.present?
  end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
	def link_image(s)
		image = s.images.where(link_image: true)
		image.first.image.remote_url
	end

	def link_image_exists(page)
		page.images.where(link_image: true).present?
	end

	def background_and_links_css(page)
		link = page.link_color.present? ? page.link_color : '#eceaf0'
		bg = page.background_color.present? ? page.background_color : '#191919'
		css = 'a {color:' + link + '} ' +
					'a:hover {color:' + link + '; ' + 'text-decoration:none;} ' +
		 			'h3 {color:' + link + '} ' +
		 			'body {background-color:' + bg + '} '
	end

end

app/views/admin/images/_image.html.haml
.span6
	.image
		= link_to image_tag(image.image.remote_url, class: 'img-rounded')
		.name= image.image_name 
		.actions
			= link_to icon("trash", "Delete Image"), admin_page_image_url(image.imageable_id, image.id), method: :delete, confirm: "Are you sure?", disable_with: "Deleting...", class: "btn btn-danger"

app/views/admin/images/_page_form.html.erb
<%= form_for([:admin, @page, @image]) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>
      <ul>
      <% @image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<%#= f.label :image, "Upload Images:" %>
	<%#= f.file_field :image, multiple: true, name: "image[image]" %>
	<%= f.hidden_field :imageable_id, :value => @page.id %>
	<%= f.hidden_field :imageable_type, :value => @page.class.to_s %>
  <div class='hero-unit drag-drop-hero'>
    <h2>Drop Images Here</h2>
    <p>Or: <%= f.file_field :image, multiple: true, name: "image[image]" %></p>
  </div>

<% end %>
<script id="template-upload" type="text/x-tmpl">
<div class="upload">
  {%=o.name%}
  <div class="progress"><div class="bar" style="width: 0%"></div></div>
</div>
</script>

app/views/admin/images/create.js.erb
<% if @image.new_record? %>
  alert("Failed to upload image: <%= j @image.errors.full_messages.join(', ').html_safe %>");
<% else %>
  $("#images").append("<%= j render(@image, @page) %>");
<% end %>

app/views/admin/images/new.html.haml
%h2= 'Gallery for ' + @page.title
= link_to 'Back', :back, class: 'btn btn-warning'
%ul.nav.nav-list
	%li.divider
.row
	#images
		= render @images
%ul.nav.nav-list
	%li.divider
.clear
	= render 'page_form'

app/views/admin/pages/_form.html.haml
= simple_form_for([:admin, @page], :html => { :class => 'form-horizontal' }) do |f|
  .span10
    = f.input :title, wrapper: :prepend, label: false do
      = content_tag :span, "Title", class: 'add-on'
      = f.input_field :title
    = f.input :content, :input_html => { :class => "span8 wysihtml5" }, label: false
    = f.input :link_color, wrapper: :prepend, label: false do
      = content_tag :span, "Link Color", class: 'add-on'
      = f.input_field :link_color, placeholder: 'Ex: #FFFF'
    
    = f.input :background_color, wrapper: :prepend, label: false do
      = content_tag :span, "Background Color", class: 'add-on'
      = f.input_field :background_color, placeholder: 'Ex: #FFFF'
    = f.input :publish, :as => :boolean
    = image_tag(@page.image.remote_url, class: 'image img-rounded span3 clear') if @page.image.present?
    = f.input :image, as: :file, label: @page.image.present? ? 'Change Link Image/Gif' : 'Add Link Image/Gif'
    
    %ul.nav.nav-list
      %li.divider
    = f.simple_fields_for :videos	do |builder|
      = render 'video_fields', f: builder
    = f.input :parent_id, as: :hidden, :input_html => {:value => @parent_page.id} if @parent_page.present?
    = f.input :parent_branch, as: :hidden, :input_html => {:value => @parent_page.title.downcase} if @parent_page.present?
    .actions
      = f.button :submit, :class => 'btn-primary'
      = link_to_add_fields "Add Video", f, :videos, class: 'btn btn-success'
      = link_to 'Back', :back, class: 'btn btn-warning'

app/views/admin/pages/_video_fields.html.haml
%fieldset
  = f.input :video, label: "Embed Video"
  = f.check_box :_destroy
  = f.label :_destroy, "Delete Video"
  = link_to "remove", '#', class: "remove_fields"

app/views/admin/pages/edit.html.haml
%h2 Edit #{@page.title}
%ul.nav.nav-list
	%li.divider
= render 'form'
/ # = link_to "Add Background Image/Gif", new_admin_page_image_path(@page), :class => 'btn btn-success'

app/views/admin/pages/index.html.haml
%table.table.table-striped
	%thead
		%tr
			%th Page
			%th Visible/Published?
			%th Last Update
			%th Created
			%th Images?
			%th Add Gallery
			%th Add Page
			%th Edit
			%th Delete
	%tbody
		- @pages.each do |p|
			- if p.parent_id == nil
				%tr
					%td
						%h4= p.title
					%td= p.publish ? "Yes" : "No"
					%td= time_ago_in_words(p.updated_at)
					%td= time_ago_in_words(p.created_at)
					%td= p.images.present? ? p.images.count : "None"
					%td
					%td= link_to icon("pencil", "Add Child Page"), admin_new_nested_path(p.id), class: "btn btn-primary"
					%td= link_to icon("edit", "Edit"), edit_admin_page_url(p.id), class: "btn btn-warning"
					%td= link_to icon("trash", "Delete page"), admin_page_url(p.id), method: :delete, confirm: "Are you sure you\'d like to delete this project?", disable_with: "Deleting...", class: "btn btn-danger"
				- if p.children.present?
					- p.children.each do |child|
						- if child.parent_branch == p.title.downcase
							%tr
								%td= icon("arrow-right", child.title)
								%td= child.publish ? "Yes" : "No"
								%td= time_ago_in_words(child.updated_at)
								%td= time_ago_in_words(child.created_at)
								%td= child.images.present? ? child.images.count : "None"
								%td= link_to icon("film", "Add Gallery"), new_admin_page_image_url(child.id), class: "btn btn-success"
								%td= link_to icon("pencil", "Add Child Page"), admin_new_nested_path(child.id), class: "btn btn-primary"
								%td= link_to icon("edit", "Edit"), edit_admin_page_path(child.id), class: "btn btn-warning"
								%td= link_to icon("trash", "Delete page"), admin_page_url(child.id), method: :delete, confirm: "Are you sure you\'d like to delete this project?", disable_with: "Deleting...", class: "btn btn-danger"
						- if child.children.present?
							- child.children.each do |child_nested|
								%tr
									%td
										= icon("arrow-right", '')
										= icon("arrow-right", child_nested.title)
									%td= child_nested.publish ? "Yes" : "No"
									%td= time_ago_in_words(child_nested.updated_at)
									%td= time_ago_in_words(child_nested.created_at)
									%td= child_nested.images.present? ? child_nested.images.count : "None"
									%td= link_to icon("film", "Add Gallery"), new_admin_page_image_url(child_nested.id), class: "btn btn-success"
									%td
									%td= link_to icon("edit", "Edit"), edit_admin_page_path(child_nested.id), class: "btn btn-warning"
									%td= link_to icon("trash", "Delete page"), admin_page_url(child_nested.id), method: :delete, confirm: "Are you sure you\'d like to delete this project?", disable_with: "Deleting...", class: "btn btn-danger"
				/ - if p.sub_pages.present?
				/ 	- p.sub_pages.each do |s|
				/ 		%tr
				/ 			%td= icon("arrow-right", s.title)
				/ 			%td= s.publish ? "Yes" : "No"
				/ 			%td= time_ago_in_words(s.updated_at)
				/ 			%td= time_ago_in_words(s.created_at)
				/ 			%td= s.images.present? ? s.images.count : "None"
				/ 			%td= link_to icon("film", "Add Images"), new_admin_page_sub_page_image_url(p.id, s.id), class: "btn btn-success"
				/ 			%td= link_to icon("pencil", "Add Sub-Page"), new_admin_page_sub_page_gallery_url(p.id, s.id), class: "btn btn-primary"
				/ 			%td= link_to icon("edit", "Edit"), edit_admin_page_sub_page_url(p.id, s.id), class: "btn btn-warning"
				/ 			%td= link_to icon("trash", "Delete page"), admin_page_sub_page_url(p.id, s.id), method: :delete, confirm: "Are you sure you\'d like to delete this project?", disable_with: "Deleting...", class: "btn btn-danger"
				/ 		- if s.galleries.present?
				/ 			- s.galleries.each do |g|
				/ 				%tr
				/ 					%td
				/ 						= icon("arrow-right", '')
				/ 						= icon("arrow-right", g.title)
				/ 					%td= g.publish ? "Yes" : "No"
				/ 					%td= time_ago_in_words(g.updated_at)
				/ 					%td= time_ago_in_words(g.created_at)
				/ 					%td= g.images.present? ? g.images.count : "None"
				/ 					%td= link_to icon("film", "Add Images"), new_admin_page_sub_page_gallery_image_url(p.id, s.id, g.id), class: "btn btn-success"
				/ 					%td
				/ 					%td= link_to icon("edit", "Edit"), edit_admin_page_sub_page_gallery_url(p.id, s.id, g.id), class: "btn btn-warning"
				/ 					%td= link_to icon("trash", "Delete page"), admin_page_sub_page_gallery_url(p.id, s.id, g.id), method: :delete, confirm: "Are you sure you\'d like to delete this project?", disable_with: "Deleting...", class: "btn btn-danger"

app/views/admin/pages/new.html.haml
%h2 New Page
%ul.nav.nav-list
	%li.divider
.row
	= render 'form'

app/views/home/index.html.haml
/ - @pages.each do |page|
/ 	%ul.unstyled
/ 		%li
/ 			%h3
/ 				= link_to page.title, page_url(page)
= content_for :extra_styles do
  = link_gifs

:javascript
  $('#home-link').hover(function(){
    $('#main').toggleClass('home-hover');
    $('.nav-link').toggleClass('home-link-hover');
  })
  $('#sound-link').hover(function(){
    $('#main').toggleClass('sound-hover');
    $('.nav-link').toggleClass('sound-link-hover');
  })
  $('#visions-link').hover(function(){
    $('#main').toggleClass('visions-hover');
    $('.nav-link').toggleClass('visions-link-hover');
  })
  $('#space-link').hover(function(){
    $('#main').toggleClass('space-hover');
    $('.nav-link').toggleClass('space-link-hover');
  })
  $('#time-link').hover(function(){
    $('#main').toggleClass('time-hover');
    $('.nav-link').toggleClass('time-link-hover');
  })

app/views/layouts/_admin_nav.html.haml
- if user_signed_in?
  = link_to "Best Friends Admin", admin_home_path, :class => 'brand'
  %ul.nav  
    %li
      = link_to 'Logout', destroy_user_session_path, :method=>'delete'
    %li
      = link_to 'Edit account', edit_user_registration_path
    %li
      = link_to 'Visit Site', root_path
- else
  = link_to "Best Friends", root_path, :class => 'brand'

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_public_nav.html.haml
#main-nav
	%ul
		- Page.published.order(:created_at).each do |page|
			- if page.parent_id.nil?
				%li.nav-links
					- if page.title == "?"
						= link_to page.title, random_url, :id => "question-link", :class => "nav-link"
					- else
						= link_to page.title, top_page_path(page), :id => "#{page.title.downcase}-link", :class => "nav-link"

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Friends"
      %meta{:content => content_for?(:description) ? yield(:description) : "Friends", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  %body.admin-body
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/admin_nav'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer
      / ! end of .container
    / ! end of #main

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Friends"
      %meta{:content => content_for?(:description) ? yield(:description) : "Derek Webers Portfolio", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        %style{:type => "text/css", :media => "all", :rel => "stylesheet"}
          = yield :extra_styles
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  %body
    #main{:role => "main"}
      .container
        .pub-content
          .row
            .span12
              = render 'layouts/messages'
              = render 'layouts/public_nav'
              = yield
          %footer
      / ! end of .container
    / ! end of #main

app/views/pages/deep_nested.html.haml
%h3= @deep_nested_page.title
- if @deep_nested_page.images.present?
  - @deep_nested_page.images.each do |i|
    .row.image-list
      .span6.image-link
        = link_to image_tag(i.image.remote_url), i.image.remote_url, class: 'fancybox', :rel => 'group'
- else
  - @deep_nested_page.videos.each do |v|
    .row.image-link-wrapper
      .span6.image-link
        = raw(v.video)
- content_for :extra_styles do
  = background_and_links_css(@deep_nested_page)

app/views/pages/nested.html.haml
%h3= @nested_page.title
- if @nested_page.images.present?
  - @nested_page.images.each do |i|
    .row.image-list
      .span6.image-link
        = link_to image_tag(i.image.remote_url), i.image.remote_url, class: 'fancybox', :rel => 'group'
- elsif @nested_page.children.published.present?
  - @nested_page.children.published.each do |s|
    .row.image-link-wrapper
      .span6.image-link
        = link_to image_tag(s.image.remote_url), deeply_nested_page_path(@page, @nested_page, s) unless s.image.blank?
      .span2.text-link
        = link_to s.title, deeply_nested_page_path(@page, @nested_page, s)
- elsif @nested_page.videos.present?
  - @nested_page.videos.each do |v|
    .row.image-link-wrapper
      .span6.image-link
        = raw(v.video)
- else
  %h2 more soon to come.. thanks!

- content_for :extra_styles do
  = background_and_links_css(@nested_page)

app/views/pages/show.html.haml
%h3= @page.title unless @page.title == "Home"
- if @page.children.published.present?
  - @page.children.published.each do |s|
    .row.image-link-wrapper
      - if s.image.present?
        .span6.image-link
          = link_to image_tag(s.image.remote_url), nested_page_path(@page, s) unless s.image.blank?
        .span2.text-link
          = link_to s.title, nested_page_path(@page, s)
      - else
        .span2.text-link
          = link_to s.title, nested_page_path(@page, s)

- elsif @page.content?
  = raw(@page.content)
- else
  %h2 more soon to come.. thanks!

- content_for :extra_styles do
  = background_and_links_css(@page)

app/views/users/index.html.haml
%h3 Users
%ul.users
  - @users.each do |user|
    %li
      = link_to user.name, user
      signed up #{user.created_at.to_date}

app/views/users/show.html.haml
%h3 User
%p
  User: #{@user.name}
%p
  Email: #{@user.email if @user.email}